Projecto_inventario/urls.py
from django.contrib import admin
from django.urls import path
from inventario import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('crear_producto/', views.crear_producto, name='crear_producto'),
    path('gestion_bodegas/', views.gestion_bodegas, name='gestion_bodegas'),
    path('crear_movimiento/', views.crear_movimiento, name='crear_movimiento'),
    path('lista_movimientos/', views.lista_movimientos, name='lista_movimientos'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('lista_productos/', views.lista_productos, name='lista_productos'),
    path('crear_detalle_movimiento/', views.crear_detalle_movimiento, name='crear_detalle_movimiento'), # Agregar esta línea
    path('crear_bodega/', views.crear_bodega, name='crear_bodega'),
    path('accounts/profile/', views.perfil_usuario, name='perfil_usuario'),
    path('', views.homepage, name='homepage'),
    
]

inventario/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, Permission

class PerfilUsuario(AbstractUser):
    JEFEBODEGA = 'JF'
    BODEGUERO = 'BD'
    ROLES_USUARIO = [
        (JEFEBODEGA, 'Jefe de Bodega'),
        (BODEGUERO, 'Bodeguero'),
    ]
    rol = models.CharField(max_length=2, choices=ROLES_USUARIO, default=BODEGUERO)

    def es_jefe_bodega(self):
        return self.rol == self.JEFEBODEGA

    def es_bodeguero(self):
        return self.rol == self.BODEGUERO
    
    groups = models.ManyToManyField(Group, related_name='perfil_usuarios')
    user_permissions = models.ManyToManyField(Permission, related_name='perfil_usuarios')

class Bodega(models.Model):
    nombre = models.CharField(max_length=100)
    direccion = models.CharField(max_length=100, default='Valor predeterminado')
    jefe_bodega = models.ForeignKey(PerfilUsuario, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.nombre

    def stock_producto(self, producto):
        return self.productos.filter(id=producto.id).count()

class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    bodegas = models.ManyToManyField(Bodega, related_name='productos')
    cantidad_producto = models.IntegerField(default=0)  # Agregamos el campo cantidad_producto como un entero con valor inicial 0

    def __str__(self):
        return self.nombre


class Movimiento(models.Model):
    bodega_origen = models.ForeignKey(Bodega, on_delete=models.CASCADE, related_name='movimientos_salida')
    bodega_destino = models.ForeignKey(Bodega, on_delete=models.CASCADE, related_name='movimientos_entrada')
    productos = models.ManyToManyField(Producto, through='DetalleMovimiento')
    usuario = models.ForeignKey(PerfilUsuario, on_delete=models.CASCADE)
    fecha = models.DateTimeField(auto_now_add=True)

class DetalleMovimiento(models.Model):
    movimiento = models.ForeignKey(Movimiento, on_delete=models.CASCADE, blank=True, null=True)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField(default=0)

inventario/forms/forms.py
from django import forms
from inventario.models import Producto, Bodega, Movimiento, DetalleMovimiento, PerfilUsuario
from django.contrib.auth.forms import UserCreationForm

class RegistroForm(UserCreationForm):
    class Meta:
        model = PerfilUsuario
        fields = ('username', 'password1', 'password2', 'rol')

class DetalleMovimientoForm(forms.ModelForm):
    class Meta:
        model = DetalleMovimiento
        fields = '__all__'

class ProductoForm(forms.ModelForm):
    bodega = forms.ModelChoiceField(queryset=Bodega.objects.all())
    cantidad = forms.IntegerField(initial=0)  # Agrega el campo de cantidad

    class Meta:
        model = Producto
        fields = ('nombre', 'descripcion', 'bodega', 'cantidad')  # Incluye el campo de cantidad en los campos del formulario


class BodegaForm(forms.ModelForm):
    class Meta:
        model = Bodega
        fields = '__all__'

class MovimientoForm(forms.ModelForm):
    class Meta:
        model = Movimiento
        fields = ('bodega_origen', 'bodega_destino', 'productos',)

inventario/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Producto, Bodega, Movimiento, DetalleMovimiento
from .forms.forms import ProductoForm, BodegaForm, MovimientoForm, RegistroForm,DetalleMovimientoForm
from .models import PerfilUsuario
from django.shortcuts import render, get_object_or_404

def register(request):
    if request.method == 'POST':
        form = RegistroForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = RegistroForm()
    return render(request, 'register.html', {'form': form})

@login_required
def crear_detalle_movimiento(request):
    if request.method == 'POST':
        form = DetalleMovimientoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('gestion_bodegas')
    else:
        form = DetalleMovimientoForm()

    return render(request, 'crear_detalle_movimiento.html', {'form': form})

@login_required
def crear_producto(request):
    # Obtener las bodegas existentes
    bodegas = Bodega.objects.all()

    if request.method == 'POST':
        form = ProductoForm(request.POST)
        if form.is_valid():
            producto = form.save(commit=False)

            # Asignar la bodega seleccionada al producto
            bodega = form.cleaned_data['bodega']
            producto.save()  # Guardamos el producto sin asignar la relación muchos a muchos

            # Agregamos la bodega al producto y guardamos nuevamente
            producto.bodegas.add(bodega)
            producto.save()

            # Obtenemos la cantidad ingresada en el formulario y la asignamos a cantidad_producto
            cantidad = form.cleaned_data['cantidad']
            producto.cantidad_producto = cantidad

            # Guardamos el producto con la cantidad_producto actualizada
            producto.save()

            # Crear el detalle de movimiento para agregar la cantidad de productos a la bodega
            DetalleMovimiento.objects.create(movimiento=None, producto=producto, cantidad=cantidad)

            return redirect('gestion_bodegas')
    else:
        form = ProductoForm()

    return render(request, 'crear_producto.html', {'form': form, 'bodegas': bodegas})



@login_required
def gestion_bodegas(request):
    bodegas = Bodega.objects.all().prefetch_related('productos', 'productos__detallemovimiento_set')

    if request.method == 'POST':
        movimiento_form = MovimientoForm(request.POST)
        if movimiento_form.is_valid():
            movimiento = movimiento_form.save(commit=False)
            movimiento.usuario = request.user
            movimiento.save()
            movimiento_form.save_m2m()
            return redirect('lista_movimientos')
    else:
        movimiento_form = MovimientoForm()

    detalles_movimiento = {}

    for bodega in bodegas:
        detalles_movimiento[bodega] = {}
        for producto in bodega.productos.all():
            detalles_movimiento[bodega][producto] = producto.detallemovimiento_set.filter(movimiento=None).first()

    return render(request, 'gestion_bodegas.html', {'bodegas': bodegas, 'detalles_movimiento': detalles_movimiento, 'movimiento_form': movimiento_form})

@login_required
def crear_bodega(request):
    if request.method == 'POST':
        form = BodegaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('gestion_bodegas')
    else:
        form = BodegaForm()
    return render(request, 'crear_bodega.html', {'form': form})

@login_required
def crear_movimiento(request):
    if request.method == 'POST':
        form = MovimientoForm(request.POST)
        if form.is_valid():
            movimiento = form.save(commit=False)
            movimiento.usuario = request.user
            movimiento.save()
            form.save_m2m()
            return redirect('lista_movimientos')
    else:
        form = MovimientoForm()
    return render(request, 'crear_movimiento.html', {'form': form})

@login_required
def lista_movimientos(request):
    movimientos = Movimiento.objects.all()
    return render(request, 'lista_movimientos.html', {'movimientos': movimientos})

@login_required
def lista_productos(request):
    productos = Producto.objects.all()
    return render(request, 'lista_productos.html', {'productos': productos})

@login_required
def perfil_usuario(request):
    # Obtener el perfil de usuario para el usuario autenticado o devolver un 404 si no existe
    perfil_usuario = get_object_or_404(PerfilUsuario, pk=request.user.id)

    # Pasar el perfil de usuario a la plantilla
    return render(request, 'perfil_usuario.html', {'perfil_usuario': perfil_usuario})

def homepage(request):
    return render(request, 'homepage.html')

inventario/templates/DetalleMovimiento.html
{% block content %}
  <h2>Detalle Movimiento</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
  </form>
{% endblock %}

inventario/templates/crear_bodega.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <title>Crear Bodega</title>
  <style>
    body {
      background-image: url('https://ferremakros.com/wp-content/uploads/2019/07/Bodegas-HD.jpg');
      background-repeat: no-repeat;
      background-size: 100% 100%; 
      background-position: center;
      margin: 0;
      padding: 0;
      font-family: Arial, sans-serif;
    }

    .crear-bodega-container {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
    }

    .form-container {
      background-color: #fff;
      padding: 20px;
      border-radius: 10px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      display: flex;
      flex-direction: column;
      align-items: center; /* Centra horizontalmente */
    }

    .crear-bodega-heading {
      color: #000;
      font-size: 24px;
      margin-bottom: 20px;
    }

    .crear-bodega-form input[type="text"] {
      width: 250px;
      height: 40px;
      padding: 10px;
      margin-bottom: 10px;
      border: 1px solid #ccc;
      border-radius: 4px;
      font-size: 16px;
    }

    .crear-bodega-button {
      background-color: #f00;
      color: #fff;
      padding: 10px 20px;
      border: none;
      border-radius: 4px;
      font-size: 16px;
      cursor: pointer;
    }

    .crear-bodega-button:hover {
      background-color: #ff5555;
    }

    .crear-bodega-button:active {
      background-color: #cc0000;
    }
  </style>
</head>
<body>
  <div class="crear-bodega-container">
    <div class="form-container">
      <h2 class="crear-bodega-heading">Crear Bodega</h2>
      <form method="post" class="crear-bodega-form">
        {% csrf_token %}
        <div class="form-field">
          <label for="{{ form.nombre.id_for_label }}">Nombre:</label>
          {{ form.nombre }}
        </div>
        <div class="form-field">
          <label for="{{ form.direccion.id_for_label }}">Dirección:</label>
          {{ form.direccion }}
        </div>
        <button type="submit" class="crear-bodega-button">Guardar</button>
      </form>
    </div>
  </div>
</body>
</html>

inventario/templates/crear_movimiento.html
{% block content %}
  <div class="crear-movimiento-container">
    <div class="form-container">
      <h2 class="crear-movimiento-heading">Generar Traspaso</h2>
      <form method="post" class="crear-movimiento-form">
        {% csrf_token %}
        <div class="form-field">
          <label for="{{ form.bodega_origen.id_for_label }}">Bodega Origen:</label>
          {{ form.bodega_origen }}
        </div>
        <div class="form-field">
          <label for="{{ form.bodega_destino.id_for_label }}">Bodega Destino:</label>
          {{ form.bodega_destino }}
        </div>
        <div class="form-field">
          <label for="{{ form.productos.id_for_label }}">Productos:</label>
          {{ form.productos }}
        </div>
        <div class="productos-info">
          {% for producto in form.productos %}
            <p>{{ producto.label_tag }} está en la bodega: {{ producto.bodega.first }}</p>
          {% endfor %}
        </div>
        <button type="submit" class="crear-movimiento-button">Guardar</button>
      </form>
    </div>
  </div>
  <style>
    /* Estilos para crear_movimiento.html */
  </style>
{% endblock %}

inventario/templates/crear_producto.html
{% block content %}
<div class="crear-producto-container">
  <div class="form-container">
    <h2 class="crear-producto-heading">Crear Producto</h2>
    <form method="post" class="crear-producto-form">
      {% csrf_token %}
      <div class="form-field">
        <label for="{{ form.nombre.id_for_label }}">Nombre Producto:</label>
        {{ form.nombre }}
      </div>
      <div class="form-field">
        <label for="{{ form.descripcion.id_for_label }}">Descripción:</label>
        {{ form.descripcion }}
      </div>
      <div class="form-field">
        <label for="{{ form.bodega.id_for_label }}">Bodega:</label>
        {{ form.bodega }}
      </div>
      <div class="form-field">
        <label for="id_cantidad">Cantidad:</label>
        <input type="number" name="cantidad" id="id_cantidad" value="{{ form.initial.cantidad }}" min="1">
      </div>
      <button type="submit" class="crear-producto-button">Guardar</button>
    </form>
  </div>
</div>
  <style>
    body {
      background-image: url('https://ferremakros.com/wp-content/uploads/2019/07/Bodegas-HD.jpg');
      background-repeat: no-repeat;
      background-size: cover;
      background-position: center;
      margin: 0;
      padding: 0;
      font-family: Arial, sans-serif;
    }

    /* Estilos para crear_producto.html */
    .crear-producto-container {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
    }

    .form-container {
      background-color: #fff;
      padding: 20px;
      border-radius: 10px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      display: flex;
      flex-direction: column;
      align-items: center;
      max-width: 400px; /* Adjust the max-width to your preference */
    }

    .crear-producto-heading {
      color: #000;
      font-size: 24px;
      /* Otros estilos de encabezado */
    }

    .form-field {
      display: flex;
      flex-direction: column;
      align-items: center;
      margin-bottom: 10px;
    }

    .form-field label {
      margin-bottom: 5px;
    }

    .crear-producto-form input[type="text"],
    .crear-producto-form input[type="number"],
    .crear-producto-form select {
      width: 150px;
      height: 40px;
      padding: 10px;
      margin-bottom: 10px;
      display: flex;
    }

    .crear-producto-button {
      background-color: #f00;
      color: #fff;
      padding: 10px 20px;
      border: none;
      border-radius: 4px;
      font-size: 16px;
      cursor: pointer;
    }

    .crear-producto-button:hover {
      background-color: #ff5555;
    }

    .crear-producto-button:active {
      background-color: #cc0000;
    }
  </style>
{% endblock %}

inventario/templates/gestion_bodegas.html
<!DOCTYPE html>
<html>
<head>
  <title>Gestión de Bodegas</title>
  <style>
    body {
      background-image: url('https://ferremakros.com/wp-content/uploads/2019/07/Bodegas-HD.jpg');
      background-repeat: no-repeat;
      background-size: 100% 100%;
      background-position: center;
      margin: 0;
      padding: 0;
    }

    .container {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
    }
   

    .gestion-bodegas-container {
      background-color: #fff;
      padding: 20px;
      border-radius: 10px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      display: flex;
      flex-direction: column; /* Agregamos flex-direction para que los elementos se apilen verticalmente */
      align-items: center; /* Centramos horizontalmente los elementos */
    }

    .bodegas-list {
      padding-right: 20px;
    }

    /* ... Otros estilos ... */
  </style>
</head>
<body>
  <div class="container">
    <div class="gestion-bodegas-container">
      <div class="bodegas-list">
        <h2 class="gestion-bodegas-heading">Bodegas</h2>
        <ul>
          {% for bodega in bodegas %}
            <li>
              {{ bodega.nombre }}
              <a href="{% url 'lista_productos' %}?bodega_id={{ bodega.id }}">Ver Productos</a>
            </li>
            <ul>
              {% for producto in bodega.productos.all %}
                <li>{{ producto.nombre }} - Stock: {{ producto.cantidad_producto }}</li>
              {% endfor %}
            </ul>
          {% endfor %}
        </ul>
      </div>

      <div class="form-container">
        <h2 class="crear-movimiento-heading">Traspaso stock</h2>
        <form method="post" class="crear-movimiento-form">
          {% csrf_token %}
          <div class="form-field">
            <label for="{{ movimiento_form.bodega_origen.id_for_label }}">Bodega Origen:</label>
            {{ movimiento_form.bodega_origen }}
          </div>
          <div class="form-field">
            <label for="{{ movimiento_form.bodega_destino.id_for_label }}">Bodega Destino:</label>
            {{ movimiento_form.bodega_destino }}
          </div>
          <div class="form-field">
            <label for="{{ movimiento_form.productos.id_for_label }}">confirmar traspaso:</label>
            {{ movimiento_form.productos }}
          </div>
          <button type="submit" class="crear-movimiento-button">Guardar</button>
        </form>
      </div>
    </div>
    <h2>Productos</h2>
    <div class="crear-producto-link">
      <a href="{% url 'crear_producto' %}" class="crear-producto-button">Crear Producto</a>
    </div>
  </div>
</body>
</html>

inventario/templates/homepage.html
{% block content %}
  <div class="homepage-container">
    <h2 class="homepage-heading">Gestor de Bodegas y Stock</h2>
    <div class="button-container">
      <a href="{% url 'register' %}" class="register-button">Registrarse</a>
      <a href="{% url 'login' %}" class="login-button">Iniciar sesión</a>
    </div>
  </div>
  <style>
    body {
      background-image: url('https://ferremakros.com/wp-content/uploads/2019/07/Bodegas-HD.jpg');
      background-repeat: no-repeat;
      background-size: cover;
      background-position: center;
      margin: 0;
      padding: 0;
      font-family: Arial, sans-serif;
    }

    .homepage-container {
      display: flex;
      justify-content: center;
      align-items: center;
      width: 400px; /* Ajusta el ancho del contenedor según tus necesidades */
      flex-direction: column;
      background-color: #fff;
      padding: 20px;
      border-radius: 10px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      margin: 0 auto; /* Centra horizontalmente el contenedor */
      margin-top: 40vh; /* Ajusta el margen superior para centrar verticalmente */
    }

    .homepage-heading {
      color: #000;
      font-size: 24px;
      margin-bottom: 20px;
    }

    .button-container {
      display: flex;
      justify-content: center;
      align-items: center;
    }

    .register-button,
    .login-button {
      background-color: #f00;
      color: #fff;
      padding: 10px 20px;
      border: none;
      border-radius: 4px;
      font-size: 16px;
      cursor: pointer;
      text-decoration: none;
      margin: 10px;
    }

    .register-button:hover,
    .login-button:hover {
      background-color: #ff5555;
    }

    .register-button:active,
    .login-button:active {
      background-color: #cc0000;
    }
  </style>
{% endblock %}

inventario/templates/lista_movimientos.html
{% block content %}
  <div class="lista-movimientos-container">
    <h2 class="lista-movimientos-heading">Lista de Movimientos</h2>
    <ul>
      {% for movimiento in movimientos %}
        <li>{{ movimiento.fecha }} - {{ movimiento.usuario }} - Origen: {{ movimiento.bodega_origen }} - Destino: {{ movimiento.bodega_destino }}</li>
      {% endfor %}
    </ul>
  </div>
  <style>
    body {
      background-image: url('https://ferremakros.com/wp-content/uploads/2019/07/Bodegas-HD.jpg');
      background-repeat: no-repeat;
      background-size: cover;
      background-position: center;
      margin: 0;
      padding: 0;
      font-family: Arial, sans-serif;
    }

    /* Estilos para lista_movimientos.html */
    .lista-movimientos-container {
      display: flex;
      justify-content: center;
      align-items: center;
      width: 400px; /* Ajusta el ancho del contenedor según tus necesidades */
      flex-direction: column;
      background-color: #fff;
      padding: 20px;
      border-radius: 10px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      margin: 0 auto; /* Centra horizontalmente el contenedor */
      margin-top: 30vh; /* Ajusta el margen superior para centrar verticalmente */
    }

    .lista-movimientos-heading {
      color: #000;
      font-size: 24px;
      margin-bottom: 20px;
    }

    ul {
      list-style: none;
      padding: 0;
      margin: 0;
    }

    li {
      margin-bottom: 10px;
      color: #000;
      font-size: 16px;
    }
  </style>
{% endblock %}

inventario/templates/lista_productos.html
{% block content %}
<div class="container">
  <div class="lista-productos-container">
    <h2 class="lista-productos-heading">Lista de Productos</h2>
    <ul class="productos-list">
      {% for producto in productos %}
        <li>
         -Nombre del Producto: {{ producto.nombre }} - Descripcion: {{ producto.descripcion }} - Bodega: 
          {% for bodega in producto.bodegas.all %}
            {{ bodega.nombre }}
          {% endfor %}
          - Cantidad: {{ producto.cantidad_producto }}
        </li>
      {% endfor %}
    </ul>
  </div>
</div>
<style>
  /* Estilos para lista_productos.html */
  body {
    background-image: url('https://ferremakros.com/wp-content/uploads/2019/07/Bodegas-HD.jpg');
    background-repeat: no-repeat;
    background-size: 100% 100%;
    background-position: center;
    margin: 0;
    padding: 0;
    font-family: Arial, sans-serif;
  }

  .container {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
  }

  .lista-productos-container {
    background-color: #fff;
    padding: 20px;
    border-radius: 10px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    display: flex;
    flex-direction: column;
    align-items: center;
    width: 40%; /* Ajusta el ancho del contenedor */
    margin: auto; /* Centra el contenedor */
  }

  .lista-productos-heading {
    color: #000;
    font-size: 24px;
    margin-bottom: 20px;
  }

  .productos-list {
    list-style: none;
    padding: 0;
  }

  .productos-list li {
    margin-bottom: 10px;
    font-size: 16px;
  }

  /* Agrega más estilos personalizados si lo deseas */
</style>
{% endblock %}

inventario/templates/login.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <title>Iniciar sesión</title>
  <style>
    body {
      background-image: url('https://ferremakros.com/wp-content/uploads/2019/07/Bodegas-HD.jpg');
      background-repeat: no-repeat;
      background-size: 100% 100%;
      background-position: center;
      margin: 0;
      padding: 0;
      font-family: Arial, sans-serif;
    }

    .login-container {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
    }

    .login-form {
      background-color: #fff;
      padding: 20px;
      border-radius: 10px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      display: flex;
      flex-direction: column;
      align-items: center; /* Centra horizontalmente */
    }

    .login-heading {
      color: #000;
      font-size: 24px;
      margin-bottom: 20px;
    }

    .login-form input[type="text"],
    .login-form input[type="password"] {
      width: 250px;
      height: 40px;
      padding: 10px;
      margin-bottom: 10px;
      border: 1px solid #ccc;
      border-radius: 4px;
      font-size: 16px;
    }

    .login-button {
      background-color: #f00;
      color: #fff;
      padding: 10px 20px;
      border: none;
      border-radius: 4px;
      font-size: 16px;
      cursor: pointer;
    }

    .login-button:hover {
      background-color: #ff5555;
    }

    .login-button:active {
      background-color: #cc0000;
    }
  </style>
</head>
<body>
  <div class="login-container">
    <div class="login-form">
      <h2 class="login-heading">Iniciar sesión</h2>
      <form method="post" class="login-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="login-button">Iniciar sesión</button>
      </form>
    </div>
  </div>
</body>
</html>

inventario/templates/perfil_usuario.html
{% block content %}
  <div class="register-container">
    <div class="form-container">
      <h2 class="perfil-usuario-heading">Perfil de Usuario</h2>
      <p>Nombre de usuario: {{ perfil_usuario.username }}</p>
      <p>Rol: {{ perfil_usuario.get_rol_display }}</p>
      <div class="button-container">
        <a href="{% url 'gestion_bodegas' %}" class="gestion-bodegas-button">Gestión de Bodegas</a>
        <!-- Add other buttons or links here to redirect to different views if needed -->
      </div>
    </div>
  </div>
  <style>
    body {
      background-image: url('https://ferremakros.com/wp-content/uploads/2019/07/Bodegas-HD.jpg');
      background-repeat: no-repeat;
      background-size: 100% 100%;
      background-attachment: fixed;
      background-position: center;
      margin: 0;
      padding: 0;
      font-family: Arial, sans-serif;
    }

    /* Estilos para perfil_usuario.html */
    .register-container {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
    }

    .form-container {
      background-color: #fff;
      padding: 20px;
      border-radius: 10px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      display: flex;
      flex-direction: column;
      align-items: center;
      max-width: 400px; /* Adjust the max-width to your preference */
    }

    .perfil-usuario-heading {
      color: #000;
      font-size: 24px;
      /* Otros estilos de encabezado */
    }

    .button-container {
      margin-top: 20px;
    }

    .gestion-bodegas-button {
      background-color: #f00;
      color: #fff;
      padding: 10px 20px;
      border: none;
      border-radius: 4px;
      font-size: 16px;
      cursor: pointer;
      text-decoration: none;
    }

    .gestion-bodegas-button:hover {
      background-color: #ff5555;
    }

    .gestion-bodegas-button:active {
      background-color: #cc0000;
    }
  </style>
{% endblock %}